#!/bin/bash

# VARIABLES POD Y DIAS ANTES
declare -a PODS=(
    "sura-provider-2-16qjd"
    "sura-server-services-9-r19ps"
    )

DIAS_ANTES=0

#CALCULA FECHA INICIAL RESTANDO DIAS ANTES
FECHA1=$(date +"%Y-%m")
DIA_DEL_MES=$(date +"%d")
DIA_FECHA_INICIAL=$(($DIA_DEL_MES - $DIAS_ANTES))
FECHA_INICIAL=${FECHA1}-${DIA_FECHA_INICIAL}

FECHA_ACTUAL=$(date +"%Y-%m-%d")


ECHO $FECHA_INICIAL
ECHO $FECHA_ACTUAL


for NAME_POD in "${PODS[@]}"
do
	#OBTENER LOGS
	FILE_LOG_POD="~/Downloads/${NAME_POD}.log"
	COMMAND_EXECUTE_GET_LOGS="oc logs ${NAME_POD} > ${FILE_LOG_POD}"
	eval $COMMAND_EXECUTE_GET_LOGS

	#FILTRA LA INFO POR FECHA INDICADA
	FILE_LOG_BY_DATE="~/Downloads/${NAME_POD}${FECHA_INICIAL}-${FECHA_ACTUAL}.log"
	COMMAND_EXECUTE="sed -n '/${FECHA_INICIAL}/,/${FECHA_ACTUAL}/p' ${FILE_LOG_POD} > ${FILE_LOG_BY_DATE}"
	eval $COMMAND_EXECUTE

	#ZIP DEL LOG
	COMMAND_ZIP="zip ${FILE_LOG_BY_DATE}.zip ~/Downloads/${NAME_POD}${FECHA_INICIAL}-${FECHA_ACTUAL}.log"
	eval $COMMAND_ZIP

	#Delete log 
	COMMAND_DELETE="rm ${FILE_LOG_POD}"
	eval $COMMAND_DELETE
	COMMAND_DELETE="rm ${FILE_LOG_BY_DATE}"
	eval $COMMAND_DELETE
	

done

